### ISSUE TITLE
VerifyError: Cannot inherit final class - DefaultHttpClient()

### ISSUE THREAD

**Issue by dexter1691** [batra-mlp-lab/mcloudcv#1]
When cloudcv.run() is executed, the code gives an exception. 
Complete traceback: 
this is the traceback:
EDU>> cv.run()
Socket Server created
New Redis Connection Formed

ans = 

  cloudcv handle

  Properties:
        params: [1x1 ConfigParser]
    upload_obj: [1x1 UploadData]
    socket_obj: [1x1 SocketConnection]

  Methods, Events, Superclasses

Exception in thread "Thread-127" java.lang.VerifyError: Cannot inherit from final class
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$000(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at com.mathworks.jmi.CustomURLClassLoader.findClass(ClassLoaderManager.java:754)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClassInternal(Unknown Source)
    at org.apache.http.impl.client.DefaultHttpClient.createHttpParams(DefaultHttpClient.java:157)
    at org.apache.http.impl.client.AbstractHttpClient.getParams(AbstractHttpClient.java:448)
    at org.apache.http.impl.client.AbstractHttpClient.createClientConnectionManager(AbstractHttpClient.java:309)
    at org.apache.http.impl.client.AbstractHttpClient.getConnectionManager(AbstractHttpClient.java:466)
    at org.apache.http.impl.client.AbstractHttpClient.createHttpContext(AbstractHttpClient.java:286)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:851)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
    at UploadData.getToken(UploadData.java:229)
    at UploadData.CloudCVPostRequest(UploadData.java:290)
    at UploadData.run(UploadData.java:394)
    at java.lang.Thread.run(Unknown Source)
Connection established
SocketID: QDonQQilKVlH8KHnysX7
SocketID: QDonQQilKVlH8KHnysX7

**Comment by yogeshbindwal** [comment]
I faced with exception :-
java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.http.impl.client.DefaultHttpClient.createHttpParams(DefaultHttpClient.java:157)
	at org.apache.http.impl.client.AbstractHttpClient.getParams(AbstractHttpClient.java:447)

please help me
